targets:
  $default:
    builders:
      freezed:
        generate_for:
          - lib/models/**/models/*.dart
      json_serializable|json_serializable:
        generate_for:
          - lib/models/**/models/*.dart