name: unit_test
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  unit_test:
    name: flutter unit test
    runs-on: ubuntu-20.04
    steps:
      - name: set up repository
        uses: actions/checkout@v2
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: flutter pub get
        run: flutter pub get
      - name: Flutter analyze
        run: flutter analyze .
      - name: flutter unit test
        run: flutter test